name: data_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - requests=2.25.0
  - pip
  # core dependencies:
  - numpy=1.19.4
  - matplotlib=3.3.3
  - pandas=1.1.4
  - jupyterlab=2.2.9
  - lxml=4.6.2
  - unicodecsv=0.14.1

